- hosts: all

  become: yes
  tasks:
    - name: install prerequisities
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
    - name: add userpermissions to docker
      shell: "usermod -aG docker muntakim"
    - name: install python3-pip
      apt:
        name: python3-pip
